apiVersion: v1
kind: ConfigMap
metadata:
  name: memehub-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://memehub-postgres:5432/regdb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  JWT_EXPIRATION: "180000"