apiVersion: apps/v1
kind: Deployment
metadata:
  name: memehub-postgres
  labels:
    app: memehub-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memehub-postgres
  template:
    metadata:
      labels:
        app: memehub-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "regdb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: memehub-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
